# all: Receiver Lector

# Receiver: Receiver.cpp
# 	g++ -Wall -Wextra -o receiver Receiver.cpp Mailbox.cpp -fno-stack-protector -pthread
# Lector: Lector.cpp
# 	g++ -Wall -Wextra -o lector Lector.cpp Mailbox.cpp
# Emitter:
# 	g++ -Wall -Wextra -o emitter Emitter.cpp Mailbox.cpp
Server:
	g++ -Wall -Wextra -o server Server.cpp


